version: '3.7'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example -d example -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - 'db:/var/lib/postgresql/data'        
    networks:
      - passin

  api-pass-in:
    build:
      context: ./api/
    container_name: api-pass-in
    ports: 
     - "3001:3333"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_BASE_URL=http://localhost:3333
    depends_on: 
      postgres:
        condition: service_healthy
    networks:
      - passin

networks:
  passin:
    driver: bridge