name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t jhonatasilva/devops_nlw:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into the container registry
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PAT }}
          ecr: false
          logout: false

      - name: Push image
        run: |
          docker push jhonatasilva/devops_nlw:${{ steps.generate_sha.outputs.sha }}
